site_name: Marvin Documentation
theme: mkdocs
nav:
- Home: index.md
- Architecture:
  - Overview: architecture/overview.md
  - Decisions: architecture/decisions.md
  - Roadmap: architecture/roadmap.md
  - Auth Provider: architecture/auth-provider.md
  - API: 
    - Overview: api/api-docs.md
    - Routes: api/route-docs.md
    - Auth: api/auth.md
    - Models:
      - Models: api/models/index.md
      - Analysis: api/models/analysis.md
      - Page: api/models/page.md
  - Components:
    - Knowledge Graph: architecture/components/knowledge-graph.md
    - LLM Service: architecture/components/llm-service.md
    - Task Engine: architecture/components/task-engine.md
    - Web Search: architecture/components/web-search.md
- Development:
  - Setup: development/setup.md
  - Conventions: development/conventions.md
  - Testing: development/testing.md
  - Security: development/security.md
  - Auth Provider Implementation: development/auth-provider.md
  - Roadmap:
    - LLM: development/llm/phase1.md
- User Guide:
  - Installation: user/installation.md
  - Getting Started: user/getting-started.md
  - Features: user/features.md
  - Privacy: user/privacy.md
- Reference:
  - API: reference/api_reference.md
  - Schemas: reference/schemas/
  - Interfaces: reference/interfaces/
  - Glossary: reference/glossary.md
